import "./global.scss";
import type { Metadata } from "next";
import AppContextProvider from "./lib/AppContext";
import Header from "./components/organisms/Header";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <AppContextProvider>
        <body>
          <Header />

          {children}
        </body>
      </AppContextProvider>
    </html>
  );
}
