import "./global.scss";
import type { Metadata } from "next";
import AppContextProvider from "./lib/AppContext";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <AppContextProvider>
        <body>{children}</body>
      </AppContextProvider>
    </html>
  );
}
